[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://www.lennin.fit/*"
  to = "https://lennin.fit/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
