[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://www.lennin.fit/*"
  to = "https://lennin.fit/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "https://tilsf.com/*"
  to = "https://lennin.fit/:splat"
  status = 301
  force = true

# Note: Success page is now handled by React Router at /success

# Disable secrets scanning for Vite environment variables
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"
