[build]
  command = "npm run build:prerender"
  publish = "dist"

# Environment variables for different contexts
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Serve TILSF static page for tilsf.com domain
[[redirects]]
  from = "/"
  to = "/tilsf.html"
  status = 200
  conditions = {Host = "tilsf.com"}
